title: Cloudflare DDNS
description: Just playing around
base: /docker-cloudflare/
dest: public
markdown:
  lineNumbers: true
themeConfig:
  repo: joshuaavalon/docker-cloudflare
  editLinks: true
  editLinkText: Edit this page on GitHub
  lastUpdated: true
  nav:
    - text: Migration
      link: /migration
  sidebar:
    - /
    - title: Guide
      collapsable: false
      children:
        - /guide/
        - /guide/cloudflare
        - /guide/configuration
    - /faq
