name: Release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  docker:
    name: Build and test Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseImage:
          - node:10-alpine
          - arm32v6/node:10-alpine
        include:
          - baseImage: node:10-alpine
            s6Arch: amd64
            dockerImage: joshava/cloudflare-ddns:latest
          - baseImage: arm32v6/node:10-alpine
            s6Arch: arm
            dockerImage: joshava/cloudflare-ddns:arm32v6
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Prepare for ARM
        if: matrix.baseImage == 'arm32v6/node:10-alpine'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build Docker image
        run: |-
          docker build \
            -t ${{ matrix.dockerImage }} \
            --build-arg BASE_IMAGE=${{ matrix.baseImage }} \
            --build-arg OVERLAY_ARCH=${{ matrix.s6Arch }} \
            .
      - name: Run unit tests
        run: docker run -i --entrypoint "" ${{ matrix.dockerImage }} npm run test
      - name: Login DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - name: Deploy
        run: docker push ${{ matrix.dockerImage }}
