name: Tag
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ghcr.io/joshuaavalon/cloudflare-ddns
          - joshava/cloudflare-ddns
        include:
          - image: ghcr.io/joshuaavalon/cloudflare-ddns
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.PERSONAL_TOKEN }}
          - image: docker.io/joshava/cloudflare-ddns
            registry: docker.io
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          image: ${{ matrix.registry }}
          tag-match: "\\d+\\.\\d+\\.\\d+"
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ matrix.username }}
          password: ${{ matrix.password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
